name: flutter_base
description: "flutter base library"
version: 2.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_base:
    git:
      url: https://gitee.com/luoyi666/dart_base.git
      ref: v2.0.1
  go_router: ^13.2.1
  dio: ^5.4.1
  cupertino_icons: ^1.0.6
  get: ^5.0.0-release-candidate-5
  collection: ^1.18.0
  hive_flutter: ^2.0.0-dev
  page_transition: ^2.1.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  hive: ^3.0.0-dev
