name: flutter_base
description: "flutter base library"
version: 2.3.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  luoyi_dart_base: ^1.0.0
  mini_getx: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.0


