name: flutter_base
description: "flutter base library"
version: 2.3.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  luoyi_flutter_base:
    git:
      url: https://gitee.com/luoyi666/luoyi_flutter_base.git
  luoyi_flutter_font: ^1.0.9
  mini_getx: ^5.0.0
  super_sliver_list: ^0.4.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.0


