name: flutter_base
description: "flutter base library"
version: 2.3.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  luoyi_flutter_base:
    git:
      url: https://github.com/luoyi58624/luoyi_flutter_base.git
  flutter_element_ui:
    git:
      url: https://github.com/luoyi58624/flutter_element_ui.git
      path: packages/flutter_element_ui
  mini_getx: ^5.0.0
  super_sliver_list: ^0.4.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.0


