name: flutter_base
description: "flutter base library"
version: 2.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_base:
    git:
      url: https://gitee.com/luoyi666/dart_base.git
      ref: v2.0.1
  go_router: ^13.2.2
  uuid: ^4.3.3
  faker: ^2.1.0
  crypto: ^3.0.3
  archive: ^3.4.10
  cupertino_icons: ^1.0.6
  get: ^5.0.0-release-candidate-5
  collection: ^1.18.0
  hive_flutter: ^2.0.0-dev
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  flutter_animate: ^4.4.1
  highlight_text: ^1.7.0
  shimmer: ^3.0.0
  open_file_plus: ^3.4.1
  flutter_html: ^3.0.0-beta.2
  file_picker: ^6.1.1
  super_sliver_list: ^0.4.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.0
  dio: ^5.4.1
  dio_smart_retry: ^5.0.0
  html: ^0.15.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  hive: ^3.0.0-dev

flutter:
  assets:
    - assets/file_icon/