name: flutter_base
description: "flutter base library"
version: 2.1.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_base:
    git:
      url: https://gitee.com/luoyi666/dart_base.git
      ref: v2.0.1
  get:
    git:
      url: https://gitee.com/luoyi666/getx.git
      ref: beta
  azlistview: ^2.0.0
  archive: ^3.4.10
  crypto: ^3.0.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  dio: ^5.4.2
  dio_smart_retry: ^6.0.0
  extended_tabs: ^4.1.0
  faker: ^2.1.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  flutter_animate: ^4.4.1
  flutter_html: ^3.0.0-beta.2
  go_router: ^13.2.3
  html: ^0.15.4
  hive_flutter: ^2.0.0-dev
  highlight_text: ^1.7.0
  lpinyin: ^2.0.3
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0
  super_sliver_list: ^0.4.0
  scrollable_positioned_list: ^0.2.3
  path_provider: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

dependency_overrides:
  hive: ^3.0.0-dev

flutter:
  assets:
    - assets/file_icon/
