name: flutter_base
description: "Flutter基础库"
version: 0.0.5
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_base:
    git:
      url: https://gitee.com/luoyi666/dart_base.git
      tag: v0.0.2
  cupertino_icons: ^1.0.6
  get: ^5.0.0-release-candidate-5
  collection: ^1.18.0
  hive_flutter: ^2.0.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  hive: ^3.0.0-dev
