name: android_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  chinese_font_library: ^1.1.0
  flutter:
    sdk: flutter
  flutter_base:
    path: ../..
  my_flutter_fonts:
    git:
      url: https://gitee.com/luoyi666/my_flutter_fonts.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

